name: hive_wrapper_generator
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.1.0
homepage: ---

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  build: ^2.0.1
  build_config: ^1.0.0
  meta: ^1.3.0
  source_gen: ^1.0.0
  code_builder: ^4.0.0
  freezed_annotation: ">=0.14.0 <2.0.0"
  # hive_wrapper:
  hive_wrapper_annotation:

dev_dependencies:
  build_test: ^2.1.0
  build_runner: ^2.0.1
  test: ^1.17.2
  matcher: ^0.12.10
  source_gen_test: ^1.0.0

dependency_overrides:
  hive_wrapper_annotation:
    path: ../hive_wrapper_annotation

#   hive_wrapper:
#     path: ../hive_wrapper
