name: hive_wrapper
description: A Wrapper and util for hive.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
 flutter:
    sdk: flutter
#  path: ^1.7.0

 hive: ^2.0.3
 hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # pedantic: ^1.11.0
  # mockito: ^5.0.0
