name: hive_wrapper
description: A Wrapper and util for hive.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  path: ^1.7.0

 hive: ^2.0.2

dev_dependencies:
  # pedantic: ^1.11.0
  test: ^1.16.8
