name: hive_wrapper
description: A Wrapper and util for hive.
version: 0.2.5+1
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  path: ^1.7.0

  hive: ^2.0.4
  hive_flutter: ^1.0.0


dev_dependencies:
  # pedantic: ^1.11.0
  test: ^1.17.3
